version: 0.2

phases:
  pre_build:
    commands:
      - echo Running maven build $environment
      - which docker
      - which java
      - mvn --version
      - docker images
      - aws --version
      - echo Logging in to Amazon ECR....
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE_NAME="aws/codebuild"
      - CODE_VERSION="1.0"
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package dockerfile:build
      - docker tag $IMAGE_NAME:latest $REPOSITORY_URI 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI
      - echo Writing image definitions file...
      - docker images
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME_DEV $REPOSITORY_URI:$CODE_VERSION > ./imagedefinitions-dev.json
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME_QA $REPOSITORY_URI:$CODE_VERSION > ./imagedefinitions-qa.json
      - cat ./imagedefinitions-dev.json
      - cat ./imagedefinitions-qa.json
artifacts:
    files: 
      - imagedefinitions-dev.json
      - imagedefinitions-qa.json
